// ESLint 9 flat config. TypeScript is covered by `npm run typecheck` because
// this repo intentionally avoids an extra TypeScript ESLint parser dependency.
const browserGlobals = {
  Audio: 'readonly',
  AudioContext: 'readonly',
  AudioWorkletNode: 'readonly',
  Blob: 'readonly',
  CanvasRenderingContext2D: 'readonly',
  CustomEvent: 'readonly',
  DOMParser: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  HTMLCanvasElement: 'readonly',
  Image: 'readonly',
  ImageCapture: 'readonly',
  KeyboardEvent: 'readonly',
  MediaRecorder: 'readonly',
  MutationObserver: 'readonly',
  Notification: 'readonly',
  ResizeObserver: 'readonly',
  URL: 'readonly',
  WebSocket: 'readonly',
  Worker: 'readonly',
  addEventListener: 'readonly',
  alert: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  clearInterval: 'readonly',
  clearTimeout: 'readonly',
  confirm: 'readonly',
  console: 'readonly',
  crypto: 'readonly',
  document: 'readonly',
  fetch: 'readonly',
  getComputedStyle: 'readonly',
  localStorage: 'readonly',
  location: 'readonly',
  module: 'readonly',
  navigator: 'readonly',
  performance: 'readonly',
  prompt: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  self: 'readonly',
  setInterval: 'readonly',
  setTimeout: 'readonly',
  window: 'readonly',
};

export default [
  {
    ignores: [
      'dist/**',
      'dist-installers/**',
      'build/**',
      'node_modules/**',
      'sidecars/**/build/**',
      'src/**/*.ts',
    ],
  },
  {
    files: ['src/renderer/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...browserGlobals,
        AudioWorkletProcessor: 'readonly',
        registerProcessor: 'readonly',
        sampleRate: 'readonly',
        aria: 'readonly',
      },
    },
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'except-parens'],
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-ex-assign': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'off',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'off',
      'no-prototype-builtins': 'off',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unused-labels': 'error',
      'no-useless-backreference': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
];
